[07/Sep/2016 00:07:14] ERROR [django.request:256] Internal Server Error: /export/typelist/
Traceback (most recent call last):
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 164, in get_response
    response = response.render()
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/template/response.py", line 158, in render
    self.content = self.rendered_content
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/template/response.py", line 135, in rendered_content
    content = template.render(context, self._request)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/template/base.py", line 210, in render
    return self._render(context)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 217, in render
    nodelist.append(node.render(context))
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 217, in render
    nodelist.append(node.render(context))
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 507, in render
    six.reraise(*exc_info)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 493, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 578, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 495, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for '' with arguments '(2, 1)' and keyword arguments '{}' not found. 0 pattern(s) tried: []
[07/Sep/2016 00:09:13] ERROR [django.request:256] Internal Server Error: /export/typedetail/2/1
Traceback (most recent call last):
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 164, in get_response
    response = response.render()
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/template/response.py", line 158, in render
    self.content = self.rendered_content
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/template/response.py", line 135, in rendered_content
    content = template.render(context, self._request)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/template/base.py", line 210, in render
    return self._render(context)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 507, in render
    six.reraise(*exc_info)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 493, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 578, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 495, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for '' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
[07/Sep/2016 00:13:10] ERROR [django.request:256] Internal Server Error: /estatebase/estatelist/
Traceback (most recent call last):
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 164, in get_response
    response = response.render()
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/template/response.py", line 158, in render
    self.content = self.rendered_content
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/template/response.py", line 135, in rendered_content
    content = template.render(context, self._request)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/template/base.py", line 210, in render
    return self._render(context)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 507, in render
    six.reraise(*exc_info)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 493, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 578, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 495, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for '' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
[07/Sep/2016 00:13:15] ERROR [django.request:256] Internal Server Error: /estatebase/estatelist/
Traceback (most recent call last):
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 164, in get_response
    response = response.render()
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/template/response.py", line 158, in render
    self.content = self.rendered_content
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/template/response.py", line 135, in rendered_content
    content = template.render(context, self._request)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/template/base.py", line 210, in render
    return self._render(context)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 507, in render
    six.reraise(*exc_info)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 493, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 578, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 495, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for '' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
[07/Sep/2016 00:14:29] ERROR [django.request:256] Internal Server Error: /estatebase/estatelist/
Traceback (most recent call last):
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 164, in get_response
    response = response.render()
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/template/response.py", line 158, in render
    self.content = self.rendered_content
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/template/response.py", line 135, in rendered_content
    content = template.render(context, self._request)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/template/base.py", line 210, in render
    return self._render(context)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 329, in render
    return nodelist.render(context)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/template/base.py", line 1273, in render
    _dict = func(*resolved_args, **resolved_kwargs)
  File "/home/picasso/Documents/DjangoSpace/estate-agent/realestate/estatebase/templatetags/paginator.py", line 45, in digg_paginator
    'previous': page_obj.previous_page_number(),
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/core/paginator.py", line 141, in previous_page_number
    return self.paginator.validate_number(self.number - 1)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/core/paginator.py", line 38, in validate_number
    raise EmptyPage('That page number is less than 1')
EmptyPage: That page number is less than 1
[07/Sep/2016 00:15:16] ERROR [django.request:256] Internal Server Error: /estatebase/clients/
Traceback (most recent call last):
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 164, in get_response
    response = response.render()
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/template/response.py", line 158, in render
    self.content = self.rendered_content
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/template/response.py", line 135, in rendered_content
    content = template.render(context, self._request)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/template/base.py", line 210, in render
    return self._render(context)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 329, in render
    return nodelist.render(context)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/template/base.py", line 1273, in render
    _dict = func(*resolved_args, **resolved_kwargs)
  File "/home/picasso/Documents/DjangoSpace/estate-agent/realestate/estatebase/templatetags/paginator.py", line 45, in digg_paginator
    'previous': page_obj.previous_page_number(),
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/core/paginator.py", line 141, in previous_page_number
    return self.paginator.validate_number(self.number - 1)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/core/paginator.py", line 38, in validate_number
    raise EmptyPage('That page number is less than 1')
EmptyPage: That page number is less than 1
[07/Sep/2016 00:21:11] ERROR [django.request:256] Internal Server Error: /estatebase/estatelist/
Traceback (most recent call last):
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/views/generic/list.py", line 174, in get
    context = self.get_context_data()
  File "/home/picasso/Documents/DjangoSpace/estate-agent/realestate/estatebase/views.py", line 400, in get_context_data
    context = super(EstateListDetailsView, self).get_context_data(**kwargs)
  File "/home/picasso/Documents/DjangoSpace/estate-agent/realestate/estatebase/views.py", line 385, in get_context_data
    'next_url': safe_next_link(self.request.get_full_path()),
  File "/home/picasso/Documents/DjangoSpace/estate-agent/realestate/estatebase/helpers/functions.py", line 14, in safe_next_link
    for k,v in next_query_dict.iteritems():
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/utils/datastructures.py", line 411, in _iteritems
    for key in self:
RuntimeError: dictionary changed size during iteration
[07/Sep/2016 00:22:40] ERROR [django.request:256] Internal Server Error: /estatebase/estatelist/
Traceback (most recent call last):
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/views/generic/list.py", line 174, in get
    context = self.get_context_data()
  File "/home/picasso/Documents/DjangoSpace/estate-agent/realestate/estatebase/views.py", line 400, in get_context_data
    context = super(EstateListDetailsView, self).get_context_data(**kwargs)
  File "/home/picasso/Documents/DjangoSpace/estate-agent/realestate/estatebase/views.py", line 385, in get_context_data
    'next_url': safe_next_link(self.request.get_full_path()),
  File "/home/picasso/Documents/DjangoSpace/estate-agent/realestate/estatebase/helpers/functions.py", line 14, in safe_next_link
    for k,v in next_query_dict.iteritems():
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/utils/datastructures.py", line 411, in _iteritems
    for key in self:
RuntimeError: dictionary changed size during iteration
[07/Sep/2016 00:35:07] ERROR [django.request:256] Internal Server Error: /devrep/partners/
Traceback (most recent call last):
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 164, in get_response
    response = response.render()
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/template/response.py", line 158, in render
    self.content = self.rendered_content
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/template/response.py", line 135, in rendered_content
    content = template.render(context, self._request)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/template/base.py", line 210, in render
    return self._render(context)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 507, in render
    six.reraise(*exc_info)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 493, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 578, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 495, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for '' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
[07/Sep/2016 00:45:35] ERROR [django.request:256] Internal Server Error: /estatebase/estatelist/
Traceback (most recent call last):
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/views/generic/list.py", line 174, in get
    context = self.get_context_data()
  File "/home/picasso/Documents/DjangoSpace/estate-agent/realestate/estatebase/views.py", line 400, in get_context_data
    context = super(EstateListDetailsView, self).get_context_data(**kwargs)
  File "/home/picasso/Documents/DjangoSpace/estate-agent/realestate/estatebase/views.py", line 385, in get_context_data
    'next_url': safe_next_link(self.request.get_full_path()),
  File "/home/picasso/Documents/DjangoSpace/estate-agent/realestate/estatebase/helpers/functions.py", line 19, in safe_next_link
    del[next_query_dict[key]]
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/http/request.py", line 386, in __delitem__
    super(QueryDict, self).__delitem__(key)
KeyError: u''
[09/Sep/2016 23:23:20] ERROR [django.request:256] Internal Server Error: /admin/auth/user/34/
Traceback (most recent call last):
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/contrib/admin/options.py", line 618, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/utils/decorators.py", line 110, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 233, in inner
    return view(request, *args, **kwargs)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1521, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/utils/decorators.py", line 34, in _wrapper
    return bound_func(*args, **kwargs)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/utils/decorators.py", line 110, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/utils/decorators.py", line 30, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/utils/decorators.py", line 145, in inner
    return func(*args, **kwargs)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1470, in changeform_view
    self.save_related(request, form, formsets, not add)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1104, in save_related
    self.save_formset(request, form, formset, change=change)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1092, in save_formset
    formset.save()
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/forms/models.py", line 636, in save
    return self.save_existing_objects(commit) + self.save_new_objects(commit)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/forms/models.py", line 753, in save_existing_objects
    saved_instances.append(self.save_existing(form, obj, commit=commit))
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/forms/models.py", line 623, in save_existing
    return form.save(commit=commit)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/forms/models.py", line 459, in save
    construct=False)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/forms/models.py", line 105, in save_instance
    instance.save()
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/db/models/base.py", line 734, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/db/models/base.py", line 762, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/db/models/base.py", line 824, in _save_table
    for f in non_pks]
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/db/models/fields/files.py", line 314, in pre_save
    file.save(file.name, file, save=False)
  File "/home/picasso/coding/venv/neorealty/local/lib/python2.7/site-packages/django/db/models/fields/files.py", line 90, in save
    name = self.field.generate_filename(self.instance, name)
  File "/home/picasso/Documents/DjangoSpace/estate-agent/realestate/estatebase/models.py", line 38, in get_profile_upload_to
    return os.path.join(u'userimages', force_unicode(instance.content_type.id), force_unicode(instance.object_id),  force_unicode(filename))
AttributeError: 'UserProfile' object has no attribute 'content_type'
[12/Sep/2016 08:13:44] ERROR [django.request:256] Internal Server Error: /estatebase/clientcreate/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/edit.py", line 249, in post
    return super(BaseCreateView, self).post(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/edit.py", line 215, in post
    return self.form_valid(form)
  File "./estatebase/views.py", line 631, in form_valid
    if contact_form.is_valid():
  File "/usr/local/lib/python2.7/dist-packages/django/forms/formsets.py", line 304, in is_valid
    self.errors
  File "/usr/local/lib/python2.7/dist-packages/django/forms/formsets.py", line 278, in errors
    self.full_clean()
  File "/usr/local/lib/python2.7/dist-packages/django/forms/formsets.py", line 327, in full_clean
    self._errors.append(form.errors)
  File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py", line 176, in errors
    self.full_clean()
  File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py", line 394, in full_clean
    self._post_clean()
  File "/usr/local/lib/python2.7/dist-packages/django/forms/models.py", line 426, in _post_clean
    self.instance.full_clean(exclude=exclude, validate_unique=False)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 1156, in full_clean
    self.clean()
  File "./estatebase/models.py", line 1213, in clean
    validate_url = URLValidator(verify_exists=False)
  File "/usr/local/lib/python2.7/dist-packages/django/core/validators.py", line 98, in __init__
    super(URLValidator, self).__init__(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'verify_exists'
[12/Sep/2016 08:15:12] ERROR [django.request:256] Internal Server Error: /estatebase/clientcreate/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/edit.py", line 249, in post
    return super(BaseCreateView, self).post(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/edit.py", line 215, in post
    return self.form_valid(form)
  File "./estatebase/views.py", line 631, in form_valid
    if contact_form.is_valid():
  File "/usr/local/lib/python2.7/dist-packages/django/forms/formsets.py", line 304, in is_valid
    self.errors
  File "/usr/local/lib/python2.7/dist-packages/django/forms/formsets.py", line 278, in errors
    self.full_clean()
  File "/usr/local/lib/python2.7/dist-packages/django/forms/formsets.py", line 327, in full_clean
    self._errors.append(form.errors)
  File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py", line 176, in errors
    self.full_clean()
  File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py", line 394, in full_clean
    self._post_clean()
  File "/usr/local/lib/python2.7/dist-packages/django/forms/models.py", line 426, in _post_clean
    self.instance.full_clean(exclude=exclude, validate_unique=False)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 1156, in full_clean
    self.clean()
  File "./estatebase/models.py", line 1213, in clean
    validate_url = URLValidator(verify_exists=False)
  File "/usr/local/lib/python2.7/dist-packages/django/core/validators.py", line 98, in __init__
    super(URLValidator, self).__init__(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'verify_exists'
[12/Sep/2016 08:20:19] ERROR [django.request:256] Internal Server Error: /estatebase/clientcreate/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/edit.py", line 249, in post
    return super(BaseCreateView, self).post(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/edit.py", line 215, in post
    return self.form_valid(form)
  File "./estatebase/views.py", line 631, in form_valid
    if contact_form.is_valid():
  File "/usr/local/lib/python2.7/dist-packages/django/forms/formsets.py", line 304, in is_valid
    self.errors
  File "/usr/local/lib/python2.7/dist-packages/django/forms/formsets.py", line 278, in errors
    self.full_clean()
  File "/usr/local/lib/python2.7/dist-packages/django/forms/formsets.py", line 327, in full_clean
    self._errors.append(form.errors)
  File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py", line 176, in errors
    self.full_clean()
  File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py", line 394, in full_clean
    self._post_clean()
  File "/usr/local/lib/python2.7/dist-packages/django/forms/models.py", line 426, in _post_clean
    self.instance.full_clean(exclude=exclude, validate_unique=False)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 1156, in full_clean
    self.clean()
  File "./estatebase/models.py", line 1213, in clean
    validate_url = URLValidator(verify_exists=False)
  File "/usr/local/lib/python2.7/dist-packages/django/core/validators.py", line 98, in __init__
    super(URLValidator, self).__init__(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'verify_exists'
[12/Sep/2016 08:20:32] ERROR [django.request:256] Internal Server Error: /estatebase/clientcreate/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/edit.py", line 249, in post
    return super(BaseCreateView, self).post(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/edit.py", line 215, in post
    return self.form_valid(form)
  File "./estatebase/views.py", line 631, in form_valid
    if contact_form.is_valid():
  File "/usr/local/lib/python2.7/dist-packages/django/forms/formsets.py", line 304, in is_valid
    self.errors
  File "/usr/local/lib/python2.7/dist-packages/django/forms/formsets.py", line 278, in errors
    self.full_clean()
  File "/usr/local/lib/python2.7/dist-packages/django/forms/formsets.py", line 327, in full_clean
    self._errors.append(form.errors)
  File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py", line 176, in errors
    self.full_clean()
  File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py", line 394, in full_clean
    self._post_clean()
  File "/usr/local/lib/python2.7/dist-packages/django/forms/models.py", line 426, in _post_clean
    self.instance.full_clean(exclude=exclude, validate_unique=False)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 1156, in full_clean
    self.clean()
  File "./estatebase/models.py", line 1213, in clean
    validate_url = URLValidator(verify_exists=False)
  File "/usr/local/lib/python2.7/dist-packages/django/core/validators.py", line 98, in __init__
    super(URLValidator, self).__init__(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'verify_exists'
[12/Sep/2016 08:20:38] ERROR [django.request:256] Internal Server Error: /estatebase/clientcreate/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/edit.py", line 249, in post
    return super(BaseCreateView, self).post(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/edit.py", line 215, in post
    return self.form_valid(form)
  File "./estatebase/views.py", line 631, in form_valid
    if contact_form.is_valid():
  File "/usr/local/lib/python2.7/dist-packages/django/forms/formsets.py", line 304, in is_valid
    self.errors
  File "/usr/local/lib/python2.7/dist-packages/django/forms/formsets.py", line 278, in errors
    self.full_clean()
  File "/usr/local/lib/python2.7/dist-packages/django/forms/formsets.py", line 327, in full_clean
    self._errors.append(form.errors)
  File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py", line 176, in errors
    self.full_clean()
  File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py", line 394, in full_clean
    self._post_clean()
  File "/usr/local/lib/python2.7/dist-packages/django/forms/models.py", line 426, in _post_clean
    self.instance.full_clean(exclude=exclude, validate_unique=False)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 1156, in full_clean
    self.clean()
  File "./estatebase/models.py", line 1213, in clean
    validate_url = URLValidator(verify_exists=False)
  File "/usr/local/lib/python2.7/dist-packages/django/core/validators.py", line 98, in __init__
    super(URLValidator, self).__init__(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'verify_exists'
[12/Sep/2016 08:20:45] ERROR [django.request:256] Internal Server Error: /estatebase/clientcreate/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/edit.py", line 249, in post
    return super(BaseCreateView, self).post(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/edit.py", line 215, in post
    return self.form_valid(form)
  File "./estatebase/views.py", line 631, in form_valid
    if contact_form.is_valid():
  File "/usr/local/lib/python2.7/dist-packages/django/forms/formsets.py", line 304, in is_valid
    self.errors
  File "/usr/local/lib/python2.7/dist-packages/django/forms/formsets.py", line 278, in errors
    self.full_clean()
  File "/usr/local/lib/python2.7/dist-packages/django/forms/formsets.py", line 327, in full_clean
    self._errors.append(form.errors)
  File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py", line 176, in errors
    self.full_clean()
  File "/usr/local/lib/python2.7/dist-packages/django/forms/forms.py", line 394, in full_clean
    self._post_clean()
  File "/usr/local/lib/python2.7/dist-packages/django/forms/models.py", line 426, in _post_clean
    self.instance.full_clean(exclude=exclude, validate_unique=False)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 1156, in full_clean
    self.clean()
  File "./estatebase/models.py", line 1213, in clean
    validate_url = URLValidator(verify_exists=False)
  File "/usr/local/lib/python2.7/dist-packages/django/core/validators.py", line 98, in __init__
    super(URLValidator, self).__init__(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'verify_exists'
